nodeAgent:
  config:
    maxLearningPeriod: 5m
    learningPeriod: 2m 
    updatePeriod: 1000000000000m #suspicion to set this to a very high value so it never updates itself
    ruleCooldown:
      ruleCooldownDuration: 0h
      ruleCooldownAfterCount: 1000000000
      ruleCooldownOnProfileFailure: false
      ruleCooldownMaxSize: 20000
capabilities:
  runtimeDetection: enable
  networkEventsStreaming: disable
  #configurations:
  #  persistence: false
  #nodeScan: disable
  #vulnerabilityScan: disable
  #relevancy: disable
  #seccompGenerator: enable
alertCRD:
  installDefault: true
  scopeClustered: true
  #scopeNamespaced: false
#persistence:
#  size:
#    backingStorage: 1Gi
clusterName: bobexample
ksNamespace: honey
excludeNamespaces: "kubescape,kube-system,kube-public,kube-node-lease,kubeconfig,gmp-system,gmp-public,honey,storm,lightening,cert-manager,openebs,kube-flannel,ingress-nginx,olm,pl,px-operator"