storage:
  image:
    repository: ghcr.io/k8sstormcenter/storage
    tag: "dev-44f0080"

nodeAgent:
  image:
    repository: ghcr.io/k8sstormcenter/node-agent
    tag: "dev-44f0080"
  config:
    maxLearningPeriod: 2m
    learningPeriod: 2m 
    updatePeriod: 10000m 
    ruleCooldown:
      ruleCooldownDuration: 0h
      ruleCooldownAfterCount: 1000000000
      ruleCooldownOnProfileFailure: false
      ruleCooldownMaxSize: 20000
capabilities:
  runtimeDetection: enable
  networkEventsStreaming: disable
alertCRD:
  installDefault: true
  scopeClustered: true
clusterName: bobexample
ksNamespace: honey
excludeNamespaces: "kubescape,kube-system,kube-public,kube-node-lease,local-path-storage,gmp-system,gmp-public,storm,lightening,cert-manager,kube-flannel,ingress-nginx,olm,px-operator,honey,pl,"
