name: Publish Helm Chart to OCI Registry

on:
  push:
    branches: [ main ]
    paths:
      - 'example/mywebapp-chart/**'
      - '.github/workflows/publish-oci-helmchart.yaml'


jobs:
  publish-oci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - uses: sigstore/cosign-installer@v3

      - name: Helm login (for helm push)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Docker login (for cosign)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Package Helm chart
        run: |
          cd example
          helm package mywebapp-chart
          CHART_VERSION=$(yq '.version' mywebapp-chart/Chart.yaml)
          CHART_NAME=$(yq '.name' mywebapp-chart/Chart.yaml)
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV
          echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV

      - name: Push Helm chart to OCI registry
        run: |
          helm push "${CHART_NAME}-${CHART_VERSION}.tgz" oci://ghcr.io/k8sstormcenter          

      - name: Sign Helm chart with Cosign (tag; digest auto-resolved)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |          
          cosign sign --yes "ghcr.io/k8sstormcenter/${CHART_NAME}:${CHART_VERSION}"          
