name: Publish Redis Helm Chart to OCI Registry

on:
  push:
    branches:
      - main
    paths:
      - 'myredis-umbrella-chart/**'
      - '.github/workflows/publish-oci-helmchart_redis.yaml'
  #pull_request:
    

jobs:
  publish-oci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Cosign
        uses: sigstore/cosign-installer@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package Helm chart
        run: |
          cd example/myredis-umbrella-chart
          helm dependency update redis-bob
          helm package redis-bob
          export CHART_VERSION=$(yq '.version' redis-bob/Chart.yaml)
          export CHART_NAME=$(yq '.name' redis-bob/Chart.yaml)
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV
          echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV

      - name: Install oras
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz
          tar -xzf oras_1.1.0_linux_amd64.tar.gz oras
          sudo mv oras /usr/local/bin/

      - name: Get chart digest
        id: digest
        run: |
          DIGEST=$(oras manifest fetch --descriptor ghcr.io/k8sstormcenter/${CHART_NAME}:${CHART_VERSION} | jq -r .digest)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "DIGEST=$DIGEST" >> $GITHUB_ENV

     # - name: Sign Helm chart with Cosign
     #   env:
     #     COSIGN_EXPERIMENTAL: "1"
     #   run: |
     #     cosign sign --yes ghcr.io/k8sstormcenter/${CHART_NAME}@${DIGEST}
     # argh, you need to tell cosign wehre the docker creds are... dont have time right now


      - name: Push Helm chart to OCI registry
        run: |
          cd example/myredis-umbrella-chart
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/k8sstormcenter