# Default values for mywebapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/k8sstormcenter/webapp
  #tag: "1.0.0" # we have digest as primary
  digest: "sha256:e323014ec9befb76bc551f8cc3bf158120150e2e277bae11844c2da6c56c0a2b"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true 
  # Annotations to add to the service account
  annotations: {}
  name: "default" 

podAnnotations: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 80

rbac:
  create: true # Set to false to disable creation of Role and RoleBinding
  roleName: webapp-role
  # serviceAccountName is taken from the serviceAccount.name above


# This section describes the settings for testing the Bill of Behaviour
# A Vendor should supply reasonable values or instructions for an end-user hereunder
bob:
  targetIp: "172.16.0.2"
  clusterName: "bobexample"